spring.application.name=login

# ERROR EN EL PUERTO: El puerto 5432 es de la DB.
# Heroku asigna el puerto en la variable $PORT. En tu PC usará el 8081.
server.port=${PORT:8084}

# ERROR DE PROTOCOLO: Heroku te da 'postgres://', pero Java requiere 'jdbc:postgresql://'
# Además, no pongas el usuario y la clave dentro de la URL de Java.
spring.datasource.url=jdbc:postgresql://cd7f19r8oktbkp.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d4vc1mbthujt4l?sslmode=require

spring.datasource.username=u72mkj40je37cb
spring.datasource.password=p0216e490b43496212c8fd11bb0b46f71cd6a43b39ad716d72771ffe9ace0a441

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Esto es opcional en Spring Boot 3, pero no estorba
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# LIMITAR CONEXIONES PARA HEROKU
# Con esto evitamos que Spring se coma las 20 conexiones permitidas
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000