spring.application.name=login
server.port=${PORT:8084}

# Credenciales de Base de Datos
spring.datasource.url=jdbc:postgresql://cd7f19r8oktbkp.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d4vc1mbthujt4l?sslmode=require
spring.datasource.username=u72mkj40je37cb
spring.datasource.password=p0216e490b43496212c8fd11bb0b46f71cd6a43b39ad716d72771ffe9ace0a441

# Configuracion de Driver y Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Pool de conexiones para Heroku
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000